### ISSUE TITLE
Déclarer votre nom d’utilisateur

### ISSUE THREAD

**Issue by emchateau** [museonum/msl6523#1]
Profil, Nom, Prénom

**Comment by zoevgdt** [comment]
zoevgdt, Vangindertael, Zoé

**Comment by chloechaspoul** [comment]
chloechaspoul, Chaspoul, Chloé

**Comment by carelkh** [comment]
carelkh, Khoury, Carel

**Comment by emchateau** [comment]
Pour information, je viens de procéder à l’ajout des personnes suivantes qui étaient déjà inscrites sur GitHub.
- @PatriciaBerube, Bérubé, Patricia
- @AlexandreLaf, Lafortune, Alexandre
- @BrogardMaelle, Brogard, Maelle

**Comment by arianeletourneau** [comment]
arianeletourneau, Létourneau, Ariane

**Comment by giselevillacorta** [comment]
giselevillacorta, Villacorta-Murcia, Gisèle

**Comment by marionrib** [comment]
Marionrib, Riberolles, Marion

**Comment by louisebrunet** [comment]
louisebrunet, Brunet, Louise

**Comment by thiagoldefreitas** [comment]
thiagoldefreitas, Freitas, Thiago

**Comment by claratissot** [comment]
claratissot, Tissot, Clara

**Comment by ialgrin** [comment]
ialgrin, Algrin, Isabelle

**Comment by Helenebrouillet** [comment]
Helenebrouillet, Brouillet, Hélène
