### ISSUE TITLE
Lundi 3 avril : changement d'horaire

### ISSUE THREAD

**Issue by zoevgdt** [museonum/msl6523#11]
Bonjour, 

Ceci est un rappel pour ceux qui sont au cours de Johanne Côté en ce début d'après-midi et qui n'auraient pas vu mon message sur Facebook. 
Nous serons au château Ramezay jusqu'à 16h et, pour nous laisser le temps de revenir jusqu'à l'UdeM, le cours de Monsieur Château commencera vers **16h30**. 

Bonne journée !

**Comment by emchateau** [comment]
@museonum/msl6523 

Merci Zoé pour le rappel. En effet, comme nous l’avions convenu ensemble la semaine dernière, le cours débute à 16H30 pour tenir compte de cette visite. 
Bien cordialement,
Emmanuel Château
