### ISSUE TITLE
UXPin

### ISSUE THREAD

**Issue by emchateau** [museonum/msl6523#13]
Bonjour à tous,
Attention au délai du compte d’essai de UXPin. Normalement celui-ci est annoncé pour trente jours. Veillez bien à faire une sauvegarde de vos données. 
En dehors de l’équipe de Marion, Louise et Patricia, qui d’entre vous utilise UXpin pour la présentation ?
Bien cordialement,
Emmanuel
@museonum/msl6523

**Comment by Helenebrouillet** [comment]
Bonjour, 
Je commence à peine à utiliser UXPin, donc il est possible que le rendu du groupe Cinéma expérimental (Ariane, Gisèle, Hélène) soit fait à partir d'UXPin mais pas certain. 
Le prestataire m'indique que mon essai ne dure que 6 jours... est-ce normal ?

Merci beaucoup et à lundi !

Hélène

**Comment by emchateau** [comment]
Bonjour,

C’est justement je pense le problème que rencontre vos camarades. Le site annonce pourtant une période d’essai de trente jours.
J’ai contacté le service pour trouver une solution.

Je reviens vers vous dès que j’en sais plus. D’ici là méfiance.

Bien cordialement,
Emmanuel Château

**Comment by emchateau** [comment]
J'aurais besoin que vous m'adressiez (par courriel) les adresses courriel utilisées pour l’inscription des membres des équipes concernées.
Bien cordialement,
Emmanuel Château

**Comment by marionrib** [comment]
marion.riberolles@umontreal.ca

On 18 April 2017 at 15:00, Emmanuel Château-Dutier <notifications@github.com

**Comment by Helenebrouillet** [comment]
Pour le groupe de cinéma expérimental il s'agit de la mienne : brouillet.helene@courrier.uqam.ca

**Comment by emchateau** [comment]
Bonjour,
J’ai le plaisir de vous informer que je suis parvenu à négocier avec UXPin une extension de vos compte pour trois mois. En toute logique, vous devriez tous disposer de cet accès avec l’adresse avec laquelle vous étiez inscrits au cours. 
Merci de prendre contact avec moi en cas de difficulté.
Je vous rappelle que je suis à votre disposition pour répondre à toutes vos questions ou en cas de besoin d’aide.
Meilleures salutations et bon courage pour la finalisation !
Emmanuel
