### ISSUE TITLE
MW17 GLAMi Winners

### ISSUE THREAD

**Issue by emchateau** [museonum/msl6523#14]
Une liste de projets récompensés à Museum and the Web 2017
http://mw17.mwconf.org/glami-winners/

@museonum/msl6523

**Comment by PatriciaBerube** [comment]
Intéressant!



Envoyé depuis mon téléphone intelligent Samsung Galaxy.


-------- Message d'origine --------
De : Emmanuel Château-Dutier <notifications@github.com>
Date : 17-04-22 09:07 (GMT-05:00)
À : museonum/msl6523 <msl6523@noreply.github.com>
Cc : PatriciaBerube <patriciaberube@hotmail.com>, Team mention <team_mention@noreply.github.com>
Objet : [museonum/msl6523] MW17 GLAMi Winners (#14)


Une liste de projets récompensés à Museum and the Web 2017
http://mw17.mwconf.org/glami-winners/

@museonum/msl6523<https://github.com/orgs/museonum/teams/msl6523>
