### ISSUE TITLE
Erreur 404 - Lien pour la lecture semaine 2

### ISSUE THREAD

**Issue by zoevgdt** [museonum/msl6523#2]
Le lien permettant d'accéder au texte _Entrée « Exposition » dans Dictionnaire Encyclopédique de Muséologie. André Desvallées et François Mairesse (dirs.). Paris : Armand Colin, 2002, pp. 133-173_.(https://github.com/museonum/biblio/blob/master/exposition.pdf) abouti à une erreur 404 (lien se trouvant dans le document msl6523/planMsl6523E-A.md).

**Comment by emchateau** [comment]
L’accès au répertoire est protégé car la diffusion du texte n’est pas libre de droit. Pour y accéder, vous devez être membre de l’organisation. Je viens de vous envoyer une invitation. 
Cordialement,
emchateau

**Comment by zoevgdt** [comment]
Merci beaucoup ! 
Cordialement, 
Zoé
