### ISSUE TITLE
Séance du 20 février

### ISSUE THREAD

**Issue by ialgrin** [museonum/msl6523#7]
Bonjour, 

pourriez-vous nous indiquer où aura lieu la séance du 20 février, qui est finalement une conférence.
Merci par avance

Isabelle

**Comment by emchateau** [comment]
Bonjour,

Comme je vous l’avais indiqué la dernière fois, et comme indiqué dans le plan de cours, la première partie du séminaire consiste en une conférence de Clarisse Bardiot sur les Culture Analytics. J’ai donc interverti la séance consacrée à la datavisualisation pour profiter de son passage au Canada.

La Conférence a d’abord lieu à Lionel Groulx en salle C-3061 au Carrefour des arts.
Nous nous transporterons ensuite, après 17h30 en salle de séminaire habituelle.

Vous trouverez une présentation de l’événement à cet endroit :
http://www.crihn.org/nouvelles/2017/02/07/conference-de-clarisse-bardiot-universite-de-valenciennes/

à demain,
Emmanuel Chateau

@museonum/msl6523
